"use client";

// ============================================================================
// FormShell — A4-sized printable wrapper used by every HR form template
// ============================================================================
//
// Every /dashboard/forms/* page wraps its content in <FormShell>. The
// shell handles:
//
//   1) A4 paper sizing (210 × 297 mm) with print-safe margins
//   2) The page-level @media print rules (hide app chrome on paper)
//   3) The download/print toolbar at the top (hidden when printing)
//   4) The branded "Generated by Nidham" footer
//
// Content INSIDE the shell is what ends up on the printed page. The
// shell itself never appears in the print output. Marked "use client"
// because the print button uses window.print().

import { useState } from "react";
import Link from "next/link";
import { DownloadPdfButton } from "@/components/download-pdf-button";

type Props = {
  /** Letterhead title for the toolbar ("HR Letter", "عقد عمل"...) */
  title: string;
  /** PDF filename (no extension) */
  filename: string;
  /** href for the "back" link in the toolbar */
  backHref?: string;
  /** href for the "print blank" link (drops ?employeeId=) */
  blankHref?: string;
  /** Pre-filled mode banner */
  preFilledFor?: string | null;
  children: React.ReactNode;
};

export function FormShell({
  title,
  filename,
  backHref = "/dashboard/forms",
  blankHref,
  preFilledFor,
  children,
}: Props) {
  // Lets HR click into the printed page and add/edit anything before printing.
  // contentEditable is DOM-level, so it works for every form with zero per-form
  // wiring; edits are captured by the print/PDF output.
  const [editing, setEditing] = useState(false);
  return (
    <>
      {/* Print-only CSS. Applied to the document so the page itself
          (not just the form) prints clean. */}
      <style>{`
        @page {
          size: A4;
          margin: 0;
        }
        @media print {
          html, body {
            background: white !important;
            margin: 0 !important;
            padding: 0 !important;
          }
          .no-print {
            display: none !important;
          }
          .form-page {
            box-shadow: none !important;
            border: none !important;
            margin: 0 !important;
            page-break-after: always;
          }
        }
        /* Force the printable page to A4 dimensions on-screen too so
           the user sees how it will print. */
        .form-page {
          width: 210mm;
          min-height: 297mm;
          margin: 0 auto;
          background: white;
        }
      `}</style>

      <div className="min-h-screen bg-slate-100 py-8 print:bg-white print:py-0">
        {/* Toolbar — hidden in print */}
        <div className="no-print max-w-4xl mx-auto mb-6 px-4 md:px-0">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div>
              <Link
                href={backHref}
                className="text-sm text-slate-500 hover:text-brand-cyan-dark font-cairo"
              >
                ← الرجوع للنماذج
              </Link>
              <h1 className="text-xl font-black font-cairo text-slate-800 mt-1">
                {title}
              </h1>
            </div>
            <div className="flex items-center gap-2 flex-wrap">
              {blankHref && (
                <Link
                  href={blankHref}
                  className="px-4 py-2 rounded-xl border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 font-bold text-sm font-cairo transition"
                >
                  📝 نموذج فارغ
                </Link>
              )}
              <button
                type="button"
                onClick={() => setEditing((e) => !e)}
                className={`px-4 py-2 rounded-xl border font-bold text-sm font-cairo transition no-print ${
                  editing
                    ? "bg-brand-cyan text-white border-brand-cyan"
                    : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
                }`}
              >
                {editing ? "✓ تم التعديل" : "✏️ تعديل النموذج"}
              </button>
              <button
                type="button"
                onClick={() => window.print()}
                className="px-4 py-2 rounded-xl border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 font-bold text-sm font-cairo transition no-print"
              >
                🖨 طباعة مباشرة
              </button>
              <DownloadPdfButton
                targetSelector="#nidham-form"
                filename={`${filename}.pdf`}
                label="📥 تحميل PDF"
              />
            </div>
          </div>

          {preFilledFor && (
            <div className="mt-3 inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold font-cairo">
              ✦ تم تعبئة النموذج تلقائياً ببيانات: {preFilledFor}
            </div>
          )}

          {editing && (
            <div className="mt-3 inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-cyan-50 border border-cyan-200 text-brand-cyan-dark text-xs font-bold font-cairo">
              ✏️ دوس على أي مكان في النموذج واكتب أو عدّل — تعديلاتك بتظهر في الطباعة والـPDF.
            </div>
          )}
        </div>

        {/* The actual printable A4 page */}
        <article
          id="nidham-form"
          contentEditable={editing}
          suppressContentEditableWarning
          className={`form-page shadow-2xl rounded-sm border print:shadow-none print:border-0 ${
            editing
              ? "border-brand-cyan ring-2 ring-brand-cyan/40 outline-none"
              : "border-slate-200"
          }`}
        >
          {children}
        </article>
      </div>
    </>
  );
}

// ----------------------------------------------------------------------------
// PrintButton client wrapper — server pages can call window.print() via
// this if needed. The FormShell already provides one in the toolbar, so
// this is exposed mainly for forms that want an in-document print link.
// ----------------------------------------------------------------------------
export function ScriptDefer() {
  return (
    <script
      dangerouslySetInnerHTML={{
        __html: `
          // Inline so server components can render a <button onclick="window.print()">
          // without dragging in a client component just for a 1-line handler.
        `,
      }}
    />
  );
}
